
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 15 12:57:19 CET 2019
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TWRITEINT = 20;
  public static final int TWRITELN = 21;
  public static final int TPTOCOMA = 28;
  public static final int TBOOLEAN = 22;
  public static final int TPUNTO = 39;
  public static final int TLTRUE = 2;
  public static final int TWHILE = 18;
  public static final int TDOSPTS = 32;
  public static final int TDIVIDE = 35;
  public static final int TDO = 17;
  public static final int TEND = 10;
  public static final int TLFALSE = 3;
  public static final int TTYPE = 26;
  public static final int TLINT = 4;
  public static final int TPROCEDURE = 15;
  public static final int TSUMA = 34;
  public static final int TCONST = 23;
  public static final int TVAR = 27;
  public static final int EOF = 0;
  public static final int TRECORD = 25;
  public static final int error = 1;
  public static final int TCOMA = 31;
  public static final int TIDENTIFICADOR = 6;
  public static final int TLSTRING = 5;
  public static final int TASSIGN = 36;
  public static final int TIGUAL = 33;
  public static final int TRETURN = 16;
  public static final int TIF = 11;
  public static final int TELSE = 13;
  public static final int TINTEGER = 24;
  public static final int TBEGIN = 9;
  public static final int TNOT = 8;
  public static final int TAND = 7;
  public static final int TPARI = 29;
  public static final int TDISTINTO = 38;
  public static final int TTHEN = 12;
  public static final int TPARD = 30;
  public static final int TMODULE = 14;
  public static final int TMENOR = 37;
  public static final int TWRITESTRING = 19;
}

